title: Rory O'Reilly # your name (or website title) here
logo: "/images/logo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description 
  <br><br>
  Second description 
  <br><br>
  View My <a href="https://www.linkedin.com/in/roryoreilly2/">LinkedIn Profile</a> 
  <br><br>
  View My <a href="https://github.com/roryoreilly/">Github Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-62085642-1 # your Google Analytics tracking ID here
