title: Rory O'Reilly # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Software developer with 3+ years of experience. Previous with Java, Python, SQL, React, JavaScript, Microservices, Machine Learning and much more.
  <br><br>
  BSc (Hons) degree in Computer Science from University College Dublin, achieving a first class honours.
  
theme: jekyll-theme-minimal
google_analytics: UA-62085642-2 # your Google Analytics tracking ID here
linkedin_url: https://www.linkedin.com/in/roryoreilly2/