title: Rory O'Reilly # your name (or website title) here
logo: "/images/logo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Software developer with 3+ years of experience. Worked in a role providing large scale data processing with Java and SQL, 
  prototyping in Python, web solutions with Java Spring, RESTful and React/JS.
  <br><br>
  Finished University College Dublin with a BSc (Hons) degree in Computer Science, achieving a first class honours.<br>
  Completed a thesis title 'Makeup Recommendation'. An application which utilised machine learning to give sets of
  makeup options to a user based on their photo. Details shown to the side.
  <br><br>
  <a href="https://www.linkedin.com/in/roryoreilly2/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-62085642-1 # your Google Analytics tracking ID here
